// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwfPpiKCa_-FjXKMXGvTOJdqKonvPN8s',
    appId: '1:769678346511:web:1f87c162463707155b967a',
    messagingSenderId: '769678346511',
    projectId: 'codice-digital-aeea8',
    authDomain: 'codice-digital-aeea8.firebaseapp.com',
    storageBucket: 'codice-digital-aeea8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4fuDfDvZhklWU6-QWce6F2mXSbjx7oxg',
    appId: '1:769678346511:android:a61c24d8c4a59fe35b967a',
    messagingSenderId: '769678346511',
    projectId: 'codice-digital-aeea8',
    storageBucket: 'codice-digital-aeea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1DxHmsQFLNHTt5XxRSg70874P4cwzMiM',
    appId: '1:769678346511:ios:f68be6d36daa40b65b967a',
    messagingSenderId: '769678346511',
    projectId: 'codice-digital-aeea8',
    storageBucket: 'codice-digital-aeea8.firebasestorage.app',
    iosBundleId: 'com.example.codiceDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1DxHmsQFLNHTt5XxRSg70874P4cwzMiM',
    appId: '1:769678346511:ios:f68be6d36daa40b65b967a',
    messagingSenderId: '769678346511',
    projectId: 'codice-digital-aeea8',
    storageBucket: 'codice-digital-aeea8.firebasestorage.app',
    iosBundleId: 'com.example.codiceDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzwfPpiKCa_-FjXKMXGvTOJdqKonvPN8s',
    appId: '1:769678346511:web:1ddc70cbbb53ce345b967a',
    messagingSenderId: '769678346511',
    projectId: 'codice-digital-aeea8',
    authDomain: 'codice-digital-aeea8.firebaseapp.com',
    storageBucket: 'codice-digital-aeea8.firebasestorage.app',
  );
}
